# Generated by Django 5.1.5 on 2025-01-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='white', max_length=20)),
                ('quality', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('custom_print', models.ImageField(blank=True, null=True, upload_to='prints/')),
            ],
        ),
    ]
