# Generated by Django 5.1.5 on 2025-01-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('tshirt', 'T-Shirt'), ('baggy', 'Baggy'), ('hoodie', 'Hoodie'), ('jumper', 'Jumper')], default='tshirt', max_length=20)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignDecal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('rot_x', models.FloatField()),
                ('rot_y', models.FloatField()),
                ('rot_z', models.FloatField()),
                ('size_x', models.FloatField(default=0.5)),
                ('size_y', models.FloatField(default=0.5)),
                ('size_z', models.FloatField(default=0.5)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decals', to='tshirt.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('rot_x', models.FloatField()),
                ('rot_y', models.FloatField()),
                ('rot_z', models.FloatField()),
                ('scale_x', models.FloatField()),
                ('scale_y', models.FloatField()),
                ('scale_z', models.FloatField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='tshirt.design')),
            ],
        ),
        migrations.DeleteModel(
            name='TShirt',
        ),
    ]
