# Generated by Django 5.1.5 on 2025-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0002_design_designdecal_designtext_delete_tshirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designdecal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='designdecal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='decals/'),
        ),
        migrations.AlterField(
            model_name='designtext',
            name='scale_x',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='designtext',
            name='scale_y',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='designtext',
            name='scale_z',
            field=models.FloatField(default=1.0),
        ),
    ]
