# Generated by Django 5.1.5 on 2025-01-15 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0003_remove_designdecal_image_url_designdecal_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a valid hex color code.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='designdecal',
            name='image',
            field=models.ImageField(upload_to='decals/'),
        ),
        migrations.AlterField(
            model_name='designtext',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a valid hex color code.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
