# Generated by Django 5.1.5 on 2025-01-15 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0004_alter_design_color_alter_design_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['user'], name='tshirt_desi_user_id_df97b1_idx'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['product'], name='tshirt_desi_product_94c48d_idx'),
        ),
    ]
